"""add route_plan solver_diagnostics and result fields

Revision ID: 50fd98403cff
Revises: 760316361124
Create Date: 2026-07-12 01:53:36.756622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fd98403cff'
down_revision: Union[str, Sequence[str], None] = '760316361124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # add the new PlanStatus enum value 'failed' (not autodetected by alembic).
    # ADD VALUE must run outside a transaction block.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE planstatus ADD VALUE IF NOT EXISTS 'failed'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_plans', sa.Column('total_unserved', sa.Integer(), nullable=True))
    op.add_column('route_plans', sa.Column('objective_value', sa.Float(), nullable=True))
    op.add_column('route_plans', sa.Column('solver_diagnostics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_plans', 'solver_diagnostics')
    op.drop_column('route_plans', 'objective_value')
    op.drop_column('route_plans', 'total_unserved')
    # ### end Alembic commands ###
    # NOTE: Postgres cannot drop an enum value; 'failed' remains on planstatus.
