"""add order service_duration_min

Revision ID: 760316361124
Revises: 3c4a7cde7ddf
Create Date: 2026-07-12 00:29:14.235377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760316361124'
down_revision: Union[str, Sequence[str], None] = '3c4a7cde7ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('service_duration_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'service_duration_min')
    # ### end Alembic commands ###
