"""initial schema

Revision ID: b160cbaf776b
Revises: 
Create Date: 2026-06-09 11:29:28.472483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b160cbaf776b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Integer(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('h3_index')
    )
    op.create_table('cost_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fuel_cost_per_km', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('driver_hourly', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_h3_index'), 'depots', ['h3_index'], unique=False)
    op.create_table('traffic_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('day_type', sa.Enum('weekday', 'friday', 'saturday', 'sunday', 'public_holiday', name='daytype'), nullable=False),
    sa.Column('hour_start', sa.Integer(), nullable=False),
    sa.Column('hour_end', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('road_type', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('synthetic', 'learned', name='trafficsource'), nullable=True),
    sa.ForeignKeyConstraint(['h3_index'], ['zones.h3_index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_profile_lookup', 'traffic_profiles', ['h3_index', 'day_type', 'hour_start', 'hour_end'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_h3_index'), 'locations', ['h3_index'], unique=False)
    op.create_table('route_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('depot_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'optimizing', 'ready', 'dispatched', 'completed', name='planstatus'), nullable=True),
    sa.Column('optimization_params', sa.JSON(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_routes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('optimized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('depot_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cost_profile_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('license_plate', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('bike', 'car', 'van', 'truck', name='vehicletype'), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_volume_m3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('avg_speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'electric', 'cng', name='fueltype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cost_profile_id'], ['cost_profiles.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('max_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pickup_location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('dropoff_location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='orderpriority'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_transit', 'delivered', 'failed', name='orderstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_windows',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('earliest', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest', sa.DateTime(timezone=True), nullable=False),
    sa.Column('penalty_per_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('driver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'cancelled', name='routestatus'), nullable=True),
    sa.Column('total_distance_m', sa.Integer(), nullable=True),
    sa.Column('total_time_sec', sa.Integer(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.Enum('depot_start', 'delivery', 'pickup', 'depot_end', name='stoptype'), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_from_prev_m', sa.Integer(), nullable=True),
    sa.Column('time_from_prev_sec', sa.Integer(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_position_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('h3_index', sa.String(length=20), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.Enum('gps', 'simulated', 'manual', name='positionsource'), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_vehicle_time', 'vehicle_position_events', ['vehicle_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_vehicle_position_events_h3_index'), 'vehicle_position_events', ['h3_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_position_events_h3_index'), table_name='vehicle_position_events')
    op.drop_index('ix_position_vehicle_time', table_name='vehicle_position_events')
    op.drop_table('vehicle_position_events')
    op.drop_table('route_stops')
    op.drop_table('routes')
    op.drop_table('delivery_windows')
    op.drop_table('orders')
    op.drop_table('drivers')
    op.drop_table('vehicles')
    op.drop_table('route_plans')
    op.drop_index(op.f('ix_locations_h3_index'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_traffic_profile_lookup', table_name='traffic_profiles')
    op.drop_table('traffic_profiles')
    op.drop_index(op.f('ix_depots_h3_index'), table_name='depots')
    op.drop_table('depots')
    op.drop_table('customers')
    op.drop_table('cost_profiles')
    op.drop_table('zones')
    op.drop_table('companies')
    # ### end Alembic commands ###
